version: 1.0
organisation: nlescsherlockdl
images:

  ## Single Shot Detection
  ssd:caffe-nv:
    context: object_detect_ssdnet/caffe-nv-ssd
  ssd:coco:
    context: object_detect_ssdnet/coco
    from: ssd:caffe-nv
  ssd:voc:
    context: object_detect_ssdnet/voc
    from: ssd:caffe-nv
  ssd:ilsvrc15:
    context: object_detect_ssdnet/ilsvrc15
    from: ssd:caffe-nv
  ssd:detect-coco:
    context: object_detect_ssdnet/coco-wrapper
    from: ssd:coco
  ssd:detect-voc:
    context: object_detect_ssdnet/voc-wrapper
    from: ssd:voc
  ssd:detect-ilsvrc15:
    context: object_detect_ssdnet/ilsvrc15-wrapper
    from: ssd:ilsvrc15

  ## Cropper
  cropper:latest:
    context: cropper

  ## Image Classify Base Images
  ## only used as dependencies, not for running
  base:caffe-nv:
    context: base/caffe-nv
  base:image_classify:
    context: base/image_classify
    from: base:caffe-nv

  ## Bare runnable images
  ## run bare Python scripts
  # any model (input option)
  cnn_classify:
    context: cnn_classify
    from: base:image_classify
  # car model
  car:color:
    context: car/color
    from: cnn_classify
  car:model:
    context: car/model
    from: cnn_classify

  ## JSON-wrapped runnable images
  ## run with cwltool; wrap bare scripts in our custom json format
  # car model
  car:color-wrapper:
    context: car/color-wrapper
    from: car:color
  car:model-wrapper:
    context: car/model-wrapper
    from: car:model

