# --------------------------
# ImageNet subset classifier
# --------------------------
#
# Description
# ---


FROM nlescsherlockdl/cuda7.5-cudnn5-devel
RUN apt update && \
    apt install -y wget
RUN wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
RUN bash miniconda.sh -b -p $HOME/miniconda
ENV PATH="/root/miniconda/bin:$PATH"
RUN conda config --set always_yes yes && \
    conda install -q pip openblas numpy scipy && \
    conda install -q keras
RUN conda install -q docopt

# Configure keras to use theano
ADD keras.json /root/.keras/
ADD imagenet.py /scripts/

# Run once to ensure weights have been downloaded
RUN python /scripts/imagenet.py /root/miniconda/share/doc/tiff-4.0.6/html/images/bali.jpg
ENTRYPOINT ["python", "/scripts/imagenet.py"]
