FROM nlescsherlockdl/caffe-nv-ssd

WORKDIR $CAFFE_ROOT
RUN wget http://www.cs.unc.edu/~wliu/projects/SSD/models_VGGNet_ilsvrc15_SSD_300x300.tar.gz \
    && tar zxvf models_VGGNet_ilsvrc15_SSD_300x300.tar.gz

